# thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
  # druid
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  # rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
  # static resources
  resources:
    add-mappings: true
    cache-period: 3600
    chain:
      cache: true
      enabled: true
      gzipped: true
      html-application-cache: true
    static-locations: classpath:/static/

# mybatis
mybatis:
  type-aliases-package: com.jesper.seckill.mapper
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapperLocations: classpath:com/jesper/seckill/mapper/*.xml

# redis
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 10
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500
